
import { VerticalBox, HorizontalBox, Button, ScrollView, Slider, AboutSlint } from "std-widgets.slint";

export struct RecentFileSlint {
    path: string,
    filename: string,
}

export struct ImageState {
    window_width: length,
    window_height: length,
    offset_x: length,
    offset_y: length,
    zoom_level: float,
    current_image: image,
    window_title: string,
}

export struct SlintColorSettings {
    gamma: float,
    contrast: float,
    brightness: float,
    hue_shift: float,      // -180.0 .. 180.0 (fok)
    saturation: float,     // -1.0 .. 1.0
    show_r: bool,
    show_g: bool,
    show_b: bool,
    invert: bool,
    sharpen_amount: float, // -1.0 .. 5.0 // realy image setting
    sharpen_radius: float, // 0.2 .. 3.0 // realy image setting
    rotate: int, // realy image setting
    oklab: bool,
}

export component ColorCorrectionWindow inherits Window {
    title: "Color Correction";
    width: 330px;
    height: 500px;
    //background: #2a2a2a;
    
    in-out property <SlintColorSettings> colset;
    callback changed();
    callback original();

    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        HorizontalLayout{
            Text { text: "Global Correction";  }
            Text { text: "                 ";  }
            Text { text: "Channels:";  }
            Rectangle { Text { text: "R"; TouchArea { mouse_cursor: pointer; clicked => {
                root.colset.show_r = !root.colset.show_r; root.changed(); } } } background: root.colset.show_r ? #88c : #888; }
            Rectangle { Text { text: "G"; TouchArea { mouse_cursor: pointer; clicked => {
                root.colset.show_g = !root.colset.show_g; root.changed(); } } } background: root.colset.show_g ? #88c : #888; }
            Rectangle { Text { text: "B"; TouchArea { mouse_cursor: pointer; clicked => {
                root.colset.show_b = !root.colset.show_b; root.changed(); } } } background: root.colset.show_b ? #88c : #888; }
            Rectangle { Text { text: "INV"; TouchArea { mouse_cursor: pointer; clicked => {
                root.colset.invert = !root.colset.invert; root.changed(); } } } background: root.colset.invert ? #88c : #888; }
        }
        VerticalLayout {
            Slider {
                value: root.colset.gamma;
                minimum: 0.1; maximum: 5.0;
                changed => {
                    root.colset.gamma = self.value;
                    root.changed();
                }
            }
            Text { text: "Gamma: " + (round(root.colset.gamma * 1000) / 1000); }
        }
        VerticalLayout {
            Slider {
                value: root.colset.contrast;
                minimum: -1.0; maximum: 1.0;
                changed => { 
                    root.colset.contrast = self.value;
                    root.changed();
                }
            }
            Text { text: "Contrast: " + (round(root.colset.contrast * 1000) / 1000); }
        }
        HorizontalLayout{
            Text { text: "Color Correction Algorithm:";  }
            Rectangle { Text { text: "Oklab (Natural)"; TouchArea { mouse_cursor: pointer; clicked => {
                root.colset.oklab = true; root.changed(); } } } background: root.colset.oklab ? #88c : #888; }
            Rectangle { Text { text: "HSV (Classic)"; TouchArea { mouse_cursor: pointer; clicked => {
                root.colset.oklab = false; root.changed(); } } } background: root.colset.oklab ? #888 : #88c; }
        }
        VerticalLayout {
            Slider {
                value: root.colset.hue_shift;
                minimum: -180.0; maximum: 180.0;
                changed => { 
                    root.colset.hue_shift = self.value;
                    root.changed();
                }
            }
            Text { text: "Hue Shift: " + (round(root.colset.hue_shift * 100) / 100); }
        }
        VerticalLayout {
            Slider {
                value: root.colset.saturation;
                minimum: -1.0; maximum: 1.0;
                changed => { 
                    root.colset.saturation = self.value;
                    root.changed();
                }
            }
            Text { text: "Saturation: " + (round(root.colset.saturation * 1000) / 1000); }
        }
        VerticalLayout {
            Slider {
                value: root.colset.brightness;
                minimum: -1.0; maximum: 1.0;
                changed => { 
                    root.colset.brightness = self.value;
                    root.changed();
                }
            }
            Text { text: "Brightness: " + (round(root.colset.brightness * 1000) / 1000); }
        }
        Text{ text: "Sharpen (Amount > 0} && Blur (Amount < 0 )"; }
        VerticalLayout {
            Slider {
                value: root.colset.sharpen_amount;
                minimum: -1.0; maximum: 9.0;
                changed => { 
                    root.colset.sharpen_amount = self.value;
                    root.changed();
                }
            }
            Text { text: "Amount: " + (round(root.colset.sharpen_amount * 1000) / 1000); }
        }
        VerticalLayout {
            Slider {
                value: root.colset.sharpen_radius;
                minimum: 0.2; maximum: 7.0;
                changed => { 
                    root.colset.sharpen_radius = self.value;
                    root.changed();
                }
            }
            Text { text: "Radius: " + (round(root.colset.sharpen_radius * 1000) / 1000); }
        }
        HorizontalLayout{
            Rectangle { Text { text: "Reset All Settings"; } TouchArea { mouse_cursor: pointer; clicked => {
                root.colset.gamma = 1.0;
                root.colset.contrast = 0.0;
                root.colset.brightness = 0.0;
                root.colset.hue_shift = 0.0;
                root.colset.saturation = 0.0;
                root.colset.show_r = true;
                root.colset.show_g = true;
                root.colset.show_b = true;
                root.colset.invert = false;
                root.colset.sharpen_amount = 0.0;
                root.colset.sharpen_radius = 0.2;
                root.colset.rotate = 0;
                root.colset.oklab = true;
                root.changed();
            } } }
            Rectangle { Text { text: "Show Original)";  } TouchArea { mouse_cursor: pointer; clicked => { root.changed(); } } }
        }
    }
}

export component InfoWindow inherits Window {
    title: "Image Information";
    width: 350px;
    height: 500px;
    background: #2a2a2a;
    
    // Itt ugyanúgy használhatod a Slidert és a többi widgetet
    in-out property <float> gamma: 1.0;
    callback changed(float);

    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        Text { text: "Képkorrekció"; font-size: 16px; }
        
        // Gamma példa
        VerticalLayout {
            Text { text: "Gamma: " + (round(root.gamma * 100) / 100); }
            Slider {
                value: root.gamma;
                minimum: 0.5; maximum: 3.0;
                changed => { 
                    root.gamma = self.value;
                    root.changed(self.value);
                }
            }
        }
        // ... többi csúszka
    }
}

export component SaveWindow inherits Window {
    title: "Mage Save ...";
    width: 350px;
    height: 500px;
    background: #2a2a2a;
    
    // Itt ugyanúgy használhatod a Slidert és a többi widgetet
    in-out property <float> gamma: 1.0;
    callback changed(float);

    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        Text { text: "Képkorrekció"; font-size: 16px; }
        
        // Gamma példa
        VerticalLayout {
            Text { text: "Gamma: " + (round(root.gamma * 100) / 100); }
            Slider {
                value: root.gamma;
                minimum: 0.5; maximum: 3.0;
                changed => { 
                    root.gamma = self.value;
                    root.changed(self.value);
                }
            }
        }
        // ... többi csúszka
    }
}



export component AboutWindow inherits Window {
    VerticalLayout {
        x: (parent.width - self.width) / 2.0;
        y: (parent.height - self.height) / 2.0;
        height:200px;
        width: 300px;
        //close-policy: close-on-click-outside;
        //close-on-click;
        Rectangle {
            background: white;
            VerticalLayout {
                Text {
                    text: "IviewSlint v1.0";
                    horizontal-alignment: center;
                    stroke-width: 1px;
                    stroke: lightblue;
                    stroke-style: center;
                    font-size: 20px;
                    color: lightblue;
                }
                Text {
                    text: "Rust & Slint alapú képnézegető";
                    horizontal-alignment: center;
                }
                Text {
                    text: "© 2026 Ferenc Takács";
                    horizontal-alignment: center;
                }
                AboutSlint {}
            }
        }
    }
}


export component MainWindow inherits Window {
    width:  root.img_state.window_width;
    height: root.img_state.window_height;
    title:  root.img_state.window_title;

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: "Open ... (O)";
                activated => { open_file(); }
            }
            MenuItem {
                title: "Reopent (R)";
                activated => { reopen_file(); }
            }
            MenuItem {
                title: @tr("Save ... (S)");
                activated => { save_file(); }
            }
            MenuItem {
                title: "Save View (Shift+S)";
                activated => { save_view(); }
            }
            Menu {
                title: @tr("Recent Paths (P)");
                for data in root.recent_files_data :
                Menu {
                    title: data.filename;
                    MenuItem {
                        title: "Open " + data.path;
                        activated => { root.open_recent(data.path); }
                    }
                    MenuItem {
                        title: "Open Here ...";
                        activated => { root.open_here_recent(data.path); }
                    }
                    MenuItem {
                        title: "Save ...";
                        activated => { root.save_recent(data.path); }
                    }
                    MenuItem {
                        title: "Save View ..,";
                        activated => { root.save_view_recent(data.path); }
                    }
                }
            }
            MenuSeparator {}
            MenuItem {
                title: @tr("Copy (Ctrl+C)");
                activated => { copy_image(); }
            }
            MenuItem {
                title: @tr("Copy View (Ctrl+Shift+C)");
                activated => { copy_view(); }
            }
            MenuItem {
                title: @tr("Paste (Ctrl+V)");
                activated => { paste_image(); }
            }
            MenuItem {
                title: @tr("Change (Ctrl+X)");
                activated => { change_image(); }
            }
            MenuItem {
                title: @tr("Change View (Ctrl+Shift+X)");
                activated => { change_view(); }
            }
            MenuSeparator {}
            MenuItem {
                title: @tr("About");
                activated => { root.show_about(); }
            }
            MenuItem {
                title: @tr("Exit (Esc)");
                activated => { exit(); }
            }
        }
        Menu {
            title: @tr("Option");
            MenuItem {
                title: @tr("Info (I)");
                activated => { show_info(); }
            }
            MenuItem {
                title: @tr("Color Setting (C)");
                activated => { color_settings(); }
            }
            Menu {
                title: @tr("Change Background (D)");
                MenuItem {
                    title: "Black";
                    //checkable: true;
                    //checked: root.background_type == 0;
                    activated => { change_background(0); }
                }
                MenuItem {
                    title: "Gray";
                    //checkable: true;
                    //checked: root.background_type == 1;
                    activated => { change_background(1); }
                }
                MenuItem {
                    title: "White";
                    //checkable: true;
                    //checked: root.background_type == 2;
                    activated => { change_background(2); }
                }
                MenuItem {
                    title: "Green";
                    //checkable: true;
                    //checked: root.background_type == 3;
                    activated => { change_background(3); }
                }
                MenuItem {
                    title: "Dark & Gray";
                    //checkable: true;
                    //checked: root.background_type == 4;
                    activated => { change_background(4); }
                }
                MenuItem {
                    title: "Green & Magenta";
                    //checkable: true;
                    //checked: root.background_type == 5;
                    activated => { change_background(5); }
                }
                MenuItem {
                    title: "Black & Brown";
                    //checkable: true;
                    //checked: root.background_type == 6;
                    activated => { change_background(6); }
                }
            }
            Menu {
                title: @tr("Rotate");
                MenuItem {
                    title: "⇅ Up (↑)";
                    activated => { up(); }
                }
                MenuItem {
                    title: "↻ Right (→)";
                    activated => { right(); }
                }
                MenuItem {
                    title: "↺ Left (←)";
                    activated => { left(); }
                }
                MenuItem {
                    title: "↥ Stand (↓)";
                    activated => { down(); }
                }
            }
            Menu {
                title: @tr("Channels hide/show");
                MenuItem {
                    title: "Red (Ctrl+R)";
                    //checkable: true;
                    //checked: root.red_checked;
                    activated => { red_channel(root.red_checked); }
                }
                MenuItem {
                    title: "Green (Ctrl+G)";
                    //checkable: true;
                    //checked: root.green_checked;
                    activated => { green_channel(root.green_checked); }
                }
                MenuItem {
                    title: "Blue (Ctrl+B)";
                    //checkable: true;
                    //checked: root.blue_checked;
                    activated => { blue_channel(root.blue_checked); }
                }
                MenuItem {
                    title: "Invert (Ctrl+I)";
                    //checkable: true;
                    //checked: root.invert_checked;
                    activated => { invert_channels(root.invert_checked); }
                }
            }
            MenuSeparator {}
            Menu {
                title: @tr("Zoom");
                MenuItem {
                    title: @tr("Fit (F)");
                    activated => { zoom(-1.0); }
                }
                MenuItem {
                    title: @tr("1:1 (1)");
                    activated => { zoom(1.0); }
                }
                MenuItem {
                    title: @tr("[0.5] (2)");
                    activated => { zoom(0.5); }
                }
                MenuItem {
                    title: @tr("[0.45] (3)");
                    activated => { zoom(0.45); }
                }
                MenuItem {
                    title: @tr("[0.4] (4)");
                    activated => { zoom(0.4); }
                }
                MenuItem {
                    title: @tr("[0.35] (5)");
                    activated => { zoom(0.35); }
                }
                MenuItem {
                    title: @tr("[0.3] (6)");
                    activated => { zoom(0.3); }
                }
                MenuItem {
                    title: @tr("[0.25] (7)");
                    activated => { zoom(0.25); }
                }
                MenuItem {
                    title: @tr("[0.2] (8)");
                    activated => { zoom(0.2); }
                }
                MenuItem {
                    title: @tr("[0.15] (9)");
                    activated => { zoom(0.15); }
                }
                MenuItem {
                    title: @tr("[0.1] (0)");
                    activated => { zoom(0.1); }
                }
                MenuItem {
                    title: @tr("[2.0] (Ctrl+2)");
                    activated => { zoom(2.0); }
                }
                MenuItem {
                    title: @tr("[3.0] (Ctrl+3)");
                    activated => { zoom(3.0); }
                }
                MenuItem {
                    title: @tr("[4.0] (Ctrl+4)");
                    activated => { zoom(4.0); }
                }
                MenuItem {
                    title: @tr("[5.0] (Ctrl+5)");
                    activated => { zoom(5.0); }
                }
                MenuItem {
                    title: @tr("[6.0] (Ctrl+6)");
                    activated => { zoom(6.0); }
                }
                MenuItem {
                    title: @tr("[7.0] (Ctrl+7)");
                    activated => { zoom(7.0); }
                }
                MenuItem {
                    title: @tr("[8.0] (Ctrl+8)");
                    activated => { zoom(8.0); }
                }
                MenuItem {
                    title: @tr("[9.0] (Ctrl+9)");
                    activated => { zoom(9.0); }
                }
            }
        }
        Menu {
            title: "Browse";
            MenuItem {
                activated => { prev_image(); }
                title: "<< (B)";
            }
            MenuItem {
                title: @tr(">> (N)");
                activated => { next_image(); }
            }
        }
        Menu {
            title: @tr("Animation");
            MenuItem {
                title: @tr("▶ Play/⏸ Stop");
                activated => { play_animation(); }
            }
            MenuItem {
                title: @tr("⏮ ⏪Begin");
                activated => { begin_animation(); }
            }
            MenuItem {
                title: @tr("◀ Back");
                activated => { back_animation(); }
            }
            MenuItem {
                title: @tr("▶ Forward");
                activated => { forward_animation(); }
            }
            MenuItem {
                title: @tr("🔁 Loop");
                checkable: true;
                activated => { loop_animation(); }
            }
        }
    }


    // image
    VerticalBox {
        padding: 0px;
        spacing: 0px;

        Rectangle {
        
            clip: true; // Ha a kép nagyobb, ne lógjon ki
            
            background: 
                root.background_type == 1 ? gray :
                root.background_type == 2 ? white :
                root.background_type == 3 ? #3c3 :
                root.background_type == 4 ? #222 :
                root.background_type == 5 ? #3b3 :  black;
 
            if ( root.background_type > 3 ) : Rectangle {            
                Image {
                    source: root.checker_tile;
                    horizontal-tiling: repeat;
                    vertical-tiling: repeat;
                    width: 100%;
                    height: 100%;
                }
            }
 
            ScrollView  {
            
                viewport-width:  img.source.width  * root.img_state.zoom_level * 1px;
                viewport-height: img.source.height * root.img_state.zoom_level * 1px;
                viewport-x: root.img_state.offset_x ;
                viewport-y: root.img_state.offset_y ;

                img := Image {
                    source: root.img_state.current_image;
                    width: parent.viewport-width;
                    height: parent.viewport-height;
                    image-fit: contain;
                }
                
                TouchArea {
                    mouse_cursor: pointer;
                    scroll_event(event) => {
                        if (root.control) {
                            if (event.delta_y > 0) {
                                root.plus(event.delta_y);
                            } else {
                                root.minus(event.delta_y);
                            }
                            return accept;
                        }
                        reject
                    }
                    pointer_event(event) => {
                        if (root.control && event.kind == PointerEventKind.move) {
                            root.mouse_move( self.mouse-x, self.mouse-y);
                            root.ctrl_event = true;
                        }
                        else if ( event.kind == PointerEventKind.cancel) {
                            root.mouse_off();
                        }
                        else {
                            root.mouse_pos( self.mouse-x, self.mouse-y);
                        }
                    }
                }

            }
        }

    }


    // Callback-ek, amiket Rust-ból fogunk meghívni/kezelni
    in-out property <ImageState> img_state:
        {
            zoom_level: 1.0,
            current_image: @image-url(""), // Ez üres képet eredményez
            window_title: "iViewer"
        };
    in-out property <image> checker_tile;
    
    private property <bool> control;
    private property <bool> ctrl_event;
    
    in property <[RecentFileSlint]> recent_files_data;
    in property <int> background_type: 0; // 0-3: egyszínű, 4-6: pepita
    callback red_channel(bool);
    in_out property <bool> red_checked;
    callback green_channel(bool);
    in_out property <bool> green_checked;
    callback blue_channel(bool);
    in_out property <bool> blue_checked;
    callback invert_channels(bool);
    in_out property <bool> invert_checked;
    
    callback mouse_move(length, length);
    callback mouse_pos(length, length);
    callback mouse_off();
    callback show_about();
    callback show_info();
    //callback show_color_settings();
    callback color_settings();
    callback open_recent(string);
    callback open_here_recent(string);
    callback save_recent(string);
    callback save_view_recent(string);
    callback change_background(int);
    callback zoom(float);
    callback up();
    callback down();
    callback left();
    callback right();
    callback plus(length);
    callback minus(length);
    callback open_file();
    callback reopen_file();
    callback save_file();
    callback save_view();
    callback copy_image();
    callback copy_view();
    callback paste_image();
    callback change_image();
    callback change_view();
    callback prev_image();
    callback next_image();
    callback play_animation();
    callback begin_animation();
    callback back_animation();
    callback forward_animation();
    callback loop_animation();
    callback exit();
    callback key_pressed_event(string, bool, bool, bool) -> bool;
    
    forward_focus: key_handler;
    key_handler := FocusScope {
        key_pressed(event) => {
            // Átadjuk a szöveget és a módosító billentyűket (Ctrl, Shift, Alt)
            root.control = event.modifiers.control;
            if( !root.control ) { root.mouse_off(); }
            if (root.key_pressed_event(event.text, root.control, event.modifiers.shift, event.modifiers.alt)) {
                return accept;
            }
            reject
        }
        key_released(event) => {
            if (!event.modifiers.control) {
                root.control = false;
            }
            reject
        }
    }

}

