
import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 800px;
    height: 600px;
    title: "IviewSlint - Image viewer";
    background: #1a1a1a;

    // Callback-ek, amiket Rust-ból fogunk meghívni/kezelni
    in-out property <image> pasted_image;
    in-out property <image> current_image;
    in-out property <float> zoom_level: 1.0;
    
    callback request_copy();
    callback request_paste();
    callback open_file();
    callback save_tiff();
    callback exit();

    VerticalBox {
        padding: 0px;
        spacing: 0px;

        Rectangle {
            height: 30px;
            background: #2d2d2d;
            HorizontalBox {
                alignment: start;
                padding: 5px;
                spacing: 15px;
                
                // Egyszerű szöveges "menük", amikre kattintva Rust-ból Dialógust nyithatsz
                Text { text: "Fájl"; color: white; touch_open := TouchArea { clicked => { root.open_file() } } }
                Text { text: "Mentés"; color: white; touch_save := TouchArea { clicked => { root.save_tiff() } } }
                Text { text: "Kilépés"; color: white; touch_exit := TouchArea { clicked => { root.exit() } } }
            }
        }

        Rectangle {
            clip: true; // Ha a kép nagyobb, ne lógjon ki
            
            Flickable { // Ez teszi lehetővé a görgetést, ha a kép nagyobb mint az ablak
                viewport-width: img.source.width * root.zoom_level * 1px;
                viewport-height: img.source.height * root.zoom_level * 1px;

                img := Image {
                    source: root.current_image;
                    width: parent.viewport-width;
                    height: parent.viewport-height;
                    image-fit: contain;
                }
            }
        }

    }

    // Globális billentyűzet figyelés
    forward_focus: my_key_handler;
    my_key_handler := FocusScope {
        key_pressed(event) => {
            if (event.modifiers.control) {
                if (event.text == "c") { root.request_copy(); return accept; }
                if (event.text == "v") { root.request_paste(); return accept; }
            }
            reject
        }
    }
}

